# Calibration file generated at 2019-06-05_192717
# These values are loaded with the startup launch file and uploaded to the IMU
# from the microcontroller.
accel_offset_x: -40
accel_offset_y: -13
accel_offset_z: -26
accel_radius: 1000
gyro_offset_x: 0
gyro_offset_y: -2
gyro_offset_z: -1
mag_offset_x: -297
mag_offset_y: -228
mag_offset_z: 89
mag_radius: 557
