# Calibration file generated at 19:35:34 on 2018-8-27
# These values are loaded with the startup launch file and uploaded to the IMU from the microcontroller.
accel_offset_x: 2
accel_offset_y: 0
accel_offset_z: 0
accel_radius: 1000
gyro_offset_x: -2
gyro_offset_y: -3
gyro_offset_z: -1
mag_offset_x: -228
mag_offset_y: 184
mag_offset_z: -264
mag_radius: 676
