# Calibration file generated at 2019-07-05_130741
# These values are loaded with the startup launch file and uploaded to the IMU
# from the microcontroller.
accel_offset_x: 14662
accel_offset_y: 4
accel_offset_z: 1
accel_radius: 0
gyro_offset_x: 2369
gyro_offset_y: 16638
gyro_offset_z: 800
mag_offset_x: 20001
mag_offset_y: 256
mag_offset_z: -448
mag_radius: 14592
